sudo: required

langauge: generic

services:
    - docker
    
before_install:
    - docker build -t jacobkhoza/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true jacobkhoza/docker-react npm run test