sudo: required

langauge: generic

services:
    - docker
    
before_install:
    - docker build -t jacobkhoza/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true jacobkhoza/docker-react npm run test
    
deploy:
    edge: true
    provider: elasticbreanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-916024457594"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"